version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "host=postgres port=5432 user=postgres password=postgres dbname=marketplace sslmode=disable"
      # MIGRATIONS_DIR: "/app/migrations" # можно включить FS-режим; без этого будет embed
    ports:
      - "8080:8080"
